version: '3.3'

services:
  api:
    build:
      dockerfile: ./deployment/DockerfileBackendApi
      context: ../

  web:
    build:
      dockerfile: ./deployment/DockerfileFrontendWeb
      context: ../

  migrations:
    build:
      dockerfile: ./deployment/DockerfileBackendMigrations
      context: ../
