version: '3.3'

services:
  api:
    build:
      dockerfile: ./deployment/DockerfileBackendApi
      context: ../
    image: no3ml3/yummycorn-api-staging

  web:
    build:
      dockerfile: ./deployment/DockerfileFrontendWeb
      context: ../
    image: no3ml3/yummycorn-web-staging

  migrations:
    build:
      dockerfile: ./deployment/DockerfileBackendMigrations
      context: ../
    image: no3ml3/yummycorn-migrations-staging

  admin:
    build:
      dockerfile: ./deployment/DockerfileAdmin
      context: ../
    image: no3ml3/yummycorn-admin-staging
